// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2K4PUCPM0nppK_Prw1IkV80SZckuuGs',
    appId: '1:1092855744374:web:dc8a1de6b56fd2ae2ddc57',
    messagingSenderId: '1092855744374',
    projectId: 'calfit-d9112',
    authDomain: 'calfit-d9112.firebaseapp.com',
    storageBucket: 'calfit-d9112.appspot.com',
    measurementId: 'G-YBH7HQ6M82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvKSVWSBAWPshpyBiNcGOPOEMhBAX8ECY',
    appId: '1:1092855744374:android:a6bff9d760488b282ddc57',
    messagingSenderId: '1092855744374',
    projectId: 'calfit-d9112',
    storageBucket: 'calfit-d9112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5_AfShg1b5MbfPstfUPLcVXs2VueEhJk',
    appId: '1:1092855744374:ios:aa2bb99e59b16da62ddc57',
    messagingSenderId: '1092855744374',
    projectId: 'calfit-d9112',
    storageBucket: 'calfit-d9112.appspot.com',
    iosClientId: '1092855744374-mjm3nscu5ous76m3hkcl18uv5ddofdi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.calFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5_AfShg1b5MbfPstfUPLcVXs2VueEhJk',
    appId: '1:1092855744374:ios:aa2bb99e59b16da62ddc57',
    messagingSenderId: '1092855744374',
    projectId: 'calfit-d9112',
    storageBucket: 'calfit-d9112.appspot.com',
    iosClientId: '1092855744374-mjm3nscu5ous76m3hkcl18uv5ddofdi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.calFit',
  );
}
